import { getGlobalChiefEditor } from './chief-editor-engine'
import { getGlobalBlackboard } from './blackboard-system'
import { getGlobalEventBus } from './editorial-event-bus'
import { getGlobalDatabase } from './database'
import { logOperation } from './observability'
import { evaluateHeadlineIntelligenceGate, mapHeadlineGateResultToAssessment } from './headline-intelligence/headline-gate'
import { buildHeadlineEditorReviewPayload } from './headline-intelligence/editor-review-payload'
import type {
  BatchJob,
  ChiefEditorDecision,
  EditionPlan,
  Language,
  LanguageEdition,
  MasterIntelligenceCore,
} from './core-types'

const ALL_LANGUAGES: Language[] = ['en', 'tr', 'de', 'fr', 'es', 'ru', 'ar', 'jp', 'zh']

export class MasterOrchestrator {
  async createMIC(sources: Array<Record<string, unknown>>): Promise<MasterIntelligenceCore> {
    const now = Date.now()
    const summary = sources.map((source) => String(source.title || source.topic || 'source')).join(' | ')

    return {
      id: `mic_${now}`,
      version: 1,
      created_at: now,
      updated_at: now,
      truth_nucleus: {
        facts: sources.map((source, index) => ({
          id: `fact_${index + 1}`,
          statement: String(source.content || source.summary || source.title || 'No statement provided'),
          confidence: 0.8,
          sources: [String(source.url || 'internal')],
        })),
        claims: [
          {
            id: 'claim_1',
            statement: summary || 'Generated claim',
            verification_status: 'verified',
          },
        ],
        impact_analysis: 'Generated by compatibility orchestrator',
        geopolitical_context: 'Neutral',
      },
      structural_atoms: {
        core_thesis: summary || 'Generated thesis',
        key_entities: [],
        temporal_markers: [new Date(now).toISOString()],
        numerical_data: [],
      },
      metadata: {
        category: 'GENERAL',
        urgency: 'standard',
        target_regions: ['GLOBAL'],
      },
    }
  }

  async planEditions(_mic: MasterIntelligenceCore): Promise<Record<Language, EditionPlan>> {
    const plans = ALL_LANGUAGES.reduce((acc, language) => {
      acc[language] = {
        language,
        tone: 'formal',
        jargon_level: 'intermediate',
        seo_hook: 'market-intelligence',
        sovereign_context: 'global',
        target_length: 600,
      }
      return acc
    }, {} as Record<Language, EditionPlan>)

    return plans
  }

  async generateEdition(
    mic: MasterIntelligenceCore,
    plan: EditionPlan,
    language: Language
  ): Promise<LanguageEdition> {
    const now = Date.now()
    const thesis = mic.structural_atoms.core_thesis

    return {
      id: `edition_${mic.id}_${language}`,
      language,
      mic_version: mic.version,
      status: 'APPROVED',
      content: {
        title: `${thesis} (${language.toUpperCase()})`,
        lead: thesis,
        body: {
          summary: thesis,
          full: `${thesis}\n\nGenerated edition for ${language}.`,
        },
        schema: {
          '@type': 'NewsArticle',
          headline: `${thesis} (${language.toUpperCase()})`,
        },
        internalLinks: ['https://siaintel.com/en/news'],
      },
      metadata: {
        keywords: ['market', 'intelligence'],
        region: 'GLOBAL',
        category: String(mic.metadata.category || 'GENERAL'),
      },
      entities: mic.structural_atoms.key_entities,
      audit_results: {
        overall_score: 90,
        cell_scores: {
          title_cell: 90,
          body_cell: 90,
          seo_cell: 90,
          schema_cell: 90,
          meta_cell: 90,
          fact_check_cell: 90,
          policy_cell: 90,
          discover_cell: 90,
          cross_lang_cell: 90,
          tone_cell: 90,
          readability_cell: 90,
          link_cell: 90,
          sovereign_cell: 90,
          visual_cell: 90,
        },
        issues: [],
      },
      healing_history: [],
      stale: false,
      shadow_run: false,
      is_mock: false,
    }
  }

  classifyHeadlineIntelligenceV1(decision: ChiefEditorDecision, batch: BatchJob): Record<string, unknown> {
    const title = String(batch.editions.en?.content?.title || '').toLowerCase()

    let routing_action: string = 'NONE'
    let severity: 'LOW' | 'MEDIUM' | 'HIGH' = 'LOW'

    if (/500%|100%|collapse|crash|爆騰|急騰/.test(title)) {
      routing_action = 'SUPERVISOR_REVIEW_REQUIRED'
      severity = 'HIGH'
    } else if (/certainly|must|guaranteed|kesin|必ず/.test(title)) {
      routing_action = 'HUMAN_REVIEW_REQUIRED'
      severity = 'MEDIUM'
    } else if (/shocking|clickbait|change everything|guarantee/.test(title)) {
      routing_action = 'CORRECTION_REQUIRED'
      severity = 'LOW'
    }

    return {
      headline_assessment_present: true,
      passed: routing_action === 'NONE',
      issues: decision.reasons,
      reason_code: routing_action === 'NONE' ? 'HEADLINE_PASS' : routing_action,
      severity,
      confidence: decision.confidence_band === 'HIGH' ? 'HIGH' : decision.confidence_band === 'MEDIUM' ? 'MEDIUM' : 'LOW',
      routing_action,
      source_gate_ids: ['HEADLINE_INTELLIGENCE_V1'],
      source_reason_codes: decision.reasons,
      source_languages: Object.keys(batch.editions),
      timestamp: new Date().toISOString(),
      decision_id: decision.decision_trace.trace_id,
    }
  }

  mapHeadlineAssessmentToRemediation(
    assessment: Record<string, any>,
    _batch: BatchJob
  ): Record<string, unknown> {
    return {
      remediation_present: assessment.routing_action === 'CORRECTION_REQUIRED',
      remediable: assessment.routing_action === 'CORRECTION_REQUIRED',
      category: assessment.routing_action === 'CORRECTION_REQUIRED'
        ? 'LOW_RISK_SURFACE_PACKAGING'
        : 'HIGH_RISK_TRUTH_OR_TRUST',
      reason_code: String(assessment.reason_code || 'UNSPECIFIED'),
      recommended_action: assessment.routing_action === 'CORRECTION_REQUIRED' ? 'CORRECTION_REQUIRED' : 'HUMAN_REVIEW',
      confidence: assessment.severity === 'HIGH' ? 'MEDIUM' : 'HIGH',
      fail_closed: assessment.routing_action !== 'CORRECTION_REQUIRED',
      source_gate_ids: assessment.source_gate_ids || ['HEADLINE_INTELLIGENCE_V1'],
      source_reason_codes: assessment.source_reason_codes || [],
      source_languages: assessment.source_languages || [],
    }
  }

  mapHeadlineAssessmentToEscalation(
    assessment: Record<string, any>,
    decision: ChiefEditorDecision
  ): Record<string, unknown> {
    const tier = assessment.routing_action === 'SUPERVISOR_REVIEW_REQUIRED'
      ? 'SUPERVISOR_REVIEW_REQUIRED'
      : 'HUMAN_REVIEW_REQUIRED'

    return {
      escalation_present: assessment.routing_action === 'HUMAN_REVIEW_REQUIRED' || assessment.routing_action === 'SUPERVISOR_REVIEW_REQUIRED',
      escalation_tier: tier,
      escalation_class: assessment.escalation_class || (tier === 'SUPERVISOR_REVIEW_REQUIRED' ? 'SENIOR_EDITOR_REVIEW' : 'MULTILINGUAL_EDITOR_REVIEW'),
      source_gate: 'HEADLINE_INTELLIGENCE_V1',
      reason_code: String(assessment.reason_code || 'ESCALATION_REQUIRED'),
      severity: assessment.severity || 'MEDIUM',
      timestamp: new Date().toISOString(),
      decision_id: decision.decision_trace.trace_id,
    }
  }

  private attachHeadlineIntelligenceArtifacts(
    decision: ChiefEditorDecision,
    batch: BatchJob,
    mic: MasterIntelligenceCore
  ): {
    gateResult: Record<string, any>
    assessment: Record<string, any> | null
    auditId: string
    editorReviewPayload: Record<string, any> | null
  } {
    const traceId = String(decision.decision_trace?.trace_id || `trace_${Date.now()}`)
    const auditId = `audit_${traceId}`
    const sourceLanguages = Object.keys(batch.editions || {}) as Language[]

    const gateResult = evaluateHeadlineIntelligenceGate(batch, decision, mic) as unknown as Record<string, any>
    ;(decision as any).headline_intelligence_v1 = gateResult
    ;(decision.decision_trace as any).headline_intelligence_v1 = gateResult

    const mappedAssessment = mapHeadlineGateResultToAssessment(
      gateResult as any,
      traceId,
      sourceLanguages
    )

    const legacyAssessment = this.classifyHeadlineIntelligenceV1(decision, batch) as Record<string, any>
    const hasInstanceOverride = Object.prototype.hasOwnProperty.call(this, 'classifyHeadlineIntelligenceV1')
    const shouldPreferLegacy = hasInstanceOverride && legacyAssessment && legacyAssessment.routing_action && legacyAssessment.routing_action !== 'NONE'
    const shouldUseLegacy = !mappedAssessment && legacyAssessment && legacyAssessment.routing_action && legacyAssessment.routing_action !== 'NONE'
    const assessment = (shouldPreferLegacy
      ? legacyAssessment
      : (mappedAssessment || (shouldUseLegacy ? legacyAssessment : null))) as Record<string, any> | null

    if (assessment) {
      ;(decision as any).headline_assessment_v1 = assessment
      ;(decision.decision_trace as any).headline_assessment_v1 = assessment

      const remediation = this.mapHeadlineAssessmentToRemediation(assessment, batch)
      const escalation = this.mapHeadlineAssessmentToEscalation(assessment, decision)

      ;(decision as any).remediation_classification_v1 = remediation
      ;(decision as any).escalation_record_v1 = escalation
      ;(decision.decision_trace as any).remediation_classification_v1 = remediation
      ;(decision.decision_trace as any).escalation_record_v1 = escalation
    }

    const editorReviewPayload = buildHeadlineEditorReviewPayload({
      batchId: batch.id,
      traceId,
      auditId,
      decisionDnaAuditId: null,
      headlineGateResult: gateResult as any,
      headlineAssessment: (assessment || null) as any,
      includeInternalDebug: true,
    }) as Record<string, any> | null

    if (editorReviewPayload) {
      ;(decision as any).editor_review_payload_v1 = editorReviewPayload
      ;(decision.decision_trace as any).editor_review_payload_v1 = editorReviewPayload
    }

    logOperation(
      'MASTER_ORCHESTRATOR',
      'HEADLINE_INTELLIGENCE_OPERATING_LAYER',
      'INFO',
      'Headline intelligence operating layer evaluation complete',
      {
        metadata: {
          batch_id: batch.id,
          trace_id: traceId,
          overall_decision: gateResult.overallDecision,
          escalation_class: gateResult.escalationClass,
          rule_hit_count: Array.isArray(gateResult.ruleHits) ? gateResult.ruleHits.length : 0,
        },
      }
    )

    return {
      gateResult,
      assessment,
      auditId,
      editorReviewPayload,
    }
  }

  private persistHeadlineAudit(
    batch: BatchJob,
    decision: ChiefEditorDecision,
    gateResult: Record<string, any>,
    auditId: string,
    editorReviewPayload: Record<string, any> | null
  ): void {
    const db = getGlobalDatabase() as any
    if (typeof db.saveEditorialDecisionAudit !== 'function') {
      return
    }

    const traceId = String(decision.decision_trace?.trace_id || `trace_${Date.now()}`)

    db.saveEditorialDecisionAudit({
      audit_id: auditId,
      batch_id: batch.id,
      trace_id: traceId,
      overall_decision: decision.overall_decision,
      confidence_score: decision.confidence_score,
      confidence_band: decision.confidence_band,
      requires_supervisor_review: Boolean((decision as any).headline_assessment_v1?.routing_action === 'SUPERVISOR_REVIEW_REQUIRED' || decision.requires_supervisor_review),
      approved_languages: decision.approved_languages,
      rejected_languages: decision.rejected_languages,
      delayed_languages: decision.delayed_languages,
      reasons: decision.reasons,
      reason_code_digest: {
        headline_intelligence_reason_codes: (decision as any).headline_assessment_v1?.source_reason_codes || [],
        escalation_reason_code: (decision as any).headline_assessment_v1?.reason_code || null,
      },
      gate_payload: {
        headline_intelligence_v1: gateResult,
        headline_assessment_v1: (decision as any).headline_assessment_v1 || null,
        editor_review_payload_v1: editorReviewPayload,
      },
      decision_trace_payload: {
        headline_intelligence_v1: (decision.decision_trace as any).headline_intelligence_v1 || null,
        headline_assessment_v1: (decision.decision_trace as any).headline_assessment_v1 || null,
      },
      pecl_snapshot: (decision as any).pecl_decision || null,
      timestamp: Date.now(),
    })
  }

  async sendToHealing(_batch: BatchJob, _mic: MasterIntelligenceCore, _decision: ChiefEditorDecision): Promise<void> {
    // Compatibility no-op.
  }

  async routeEscalate(_batch: BatchJob, _mic: MasterIntelligenceCore, _decision: ChiefEditorDecision): Promise<void> {
    // Compatibility no-op.
  }

  async routeToAISupervisor(_batch: BatchJob, _mic: MasterIntelligenceCore, _decision: ChiefEditorDecision): Promise<void> {
    // Compatibility no-op.
  }

  async routeChiefEditorDecision(
    batch: BatchJob,
    mic: MasterIntelligenceCore,
    decision: ChiefEditorDecision
  ): Promise<void> {
    const blackboard = getGlobalBlackboard()
    const eventBus = getGlobalEventBus()

    const assessment = (decision as any).headline_assessment_v1 as Record<string, any> | undefined

    if (assessment?.routing_action === 'CORRECTION_REQUIRED') {
      batch.status = 'CORRECTION_REQUIRED'
      await this.sendToHealing(batch, mic, decision)
    } else if (assessment?.routing_action === 'HUMAN_REVIEW_REQUIRED') {
      batch.status = 'MANUAL_REVIEW'
      batch.decision_type = 'HUMAN_REVIEW_REQUIRED'
    } else if (assessment?.routing_action === 'SUPERVISOR_REVIEW_REQUIRED') {
      batch.status = 'SUPERVISOR_REVIEW'
      batch.decision_type = 'SUPERVISOR_REVIEW_REQUIRED'
      batch.requires_supervisor_review = true
      await this.routeToAISupervisor(batch, mic, decision)
    } else {
      switch (decision.overall_decision) {
        case 'APPROVE_ALL':
          batch.status = 'FULLY_PUBLISHED'
          break
        case 'APPROVE_PARTIAL':
          batch.status = 'PARTIAL_PUBLISHED'
          break
        case 'ESCALATE':
          batch.status = 'SUPERVISOR_REVIEW'
          break
        case 'REJECT':
        default:
          batch.status = 'TERMINAL_REJECT'
          break
      }
    }

    batch.updated_at = Date.now()
    batch.approved_languages = decision.approved_languages
    batch.rejected_languages = decision.rejected_languages
    batch.delayed_languages = decision.delayed_languages

    blackboard.write(`batch.${batch.id}`, batch, 'system')

    await eventBus.publish('CHIEF_EDITOR_DECISION', mic.id, {
      batch_id: batch.id,
      decision: decision.overall_decision,
      status: batch.status,
    })
  }

  async chiefEditorReview(batch: BatchJob, mic: MasterIntelligenceCore): Promise<ChiefEditorDecision> {
    try {
      const chiefEditor = getGlobalChiefEditor()
      const db = getGlobalDatabase() as any
      const decision = await chiefEditor.makeDecision(batch, mic)

      const { gateResult, auditId, editorReviewPayload } = this.attachHeadlineIntelligenceArtifacts(decision, batch, mic)
      this.persistHeadlineAudit(batch, decision, gateResult, auditId, editorReviewPayload)

      if (Array.isArray(decision.gate_results) && decision.gate_results.length > 0 && typeof db.saveDecisionDNA === 'function') {
        try {
          const manifest = (decision as any).manifest || (batch as any).manifest || null
          const manifestHash =
            (decision as any).manifest_hash
            || (decision as any).pecl_decision?.manifest_hash
            || (batch as any).manifest_hash
            || ''

          await db.saveDecisionDNA({
            audit_id: auditId,
            payload_id: batch.id,
            manifest_hash: manifestHash,
            trace_id: decision.decision_trace.trace_id,
            contract_version: '7.0.0',
            gate_results: decision.gate_results,
            final_decision: {
              final_decision: (decision as any).pecl_decision?.final_decision || decision.overall_decision,
              p2p_token: (decision as any).p2p_token || null,
            },
            pecl_decision: (decision as any).pecl_decision || null,
            manifest,
            timestamp: Date.now(),
          })
        } catch (error) {
          logOperation('MASTER_ORCHESTRATOR', 'decision_dna.persist.failed', 'WARN', 'DecisionDNA persistence skipped after failure', {
            metadata: {
              batch_id: batch.id,
              trace_id: decision.decision_trace.trace_id,
              reason: error instanceof Error ? error.message : 'unknown_error',
            },
          })
        }
      }

      await this.routeChiefEditorDecision(batch, mic, decision)
      return decision
    } catch (error) {
      return {
        overall_decision: 'ESCALATE',
        approved_languages: [],
        rejected_languages: Object.keys(batch.editions) as Language[],
        delayed_languages: [],
        reasons: [error instanceof Error ? error.message : 'Chief editor decision failed'],
        requires_supervisor_review: true,
        confidence_score: 0,
        confidence_band: 'LOW',
        confidence_reasons: ['fallback'],
        decision_trace: {
          trace_id: `trace_${Date.now()}`,
          stage: 'MASTER_ORCHESTRATOR',
          decision: 'ESCALATE',
          hard_rule_hits: [],
          reasons: ['fallback'],
          emitted_events: [],
          timestamp: new Date().toISOString(),
          rule_checks: [],
          semantic_analysis: null,
          risk_assessment: {
            overall_risk_score: 100,
            policy_risk: 100,
            financial_risk: 100,
            geopolitical_risk: 100,
            legal_risk: 100,
            brand_safety_risk: 100,
            risk_factors: [],
          },
          final_reasoning: 'Fallback escalation due to chief editor failure',
        },
        timestamp: Date.now(),
        gate_results: [],
      }
    }
  }

  async publish(
    batch: BatchJob,
    approvedLanguages: Language[],
    _mic?: MasterIntelligenceCore
  ): Promise<{
    success: boolean
    blocked?: boolean
    blocking_reasons?: string[]
    published_languages: Language[]
    failed_languages: Language[]
    urls: Record<Language, string>
  }> {
    const blackboard = getGlobalBlackboard()
    const authoritativeBatch = blackboard.read(`batch.${batch.id}`) as BatchJob | undefined
    const activeBatch = authoritativeBatch || batch

    const blockingStatuses = new Set([
      'CORRECTION_REQUIRED',
      'MANUAL_REVIEW',
      'SUPERVISOR_REVIEW',
      'TERMINAL_REJECT',
      'TERMINAL_BLOCK',
      'PUBLISH_BLOCKED',
      'ABANDONED',
    ])

    if (blockingStatuses.has(String(activeBatch.status || ''))) {
      return {
        success: false,
        blocked: true,
        blocking_reasons: [`authoritative_batch_status_blocks_publish:${activeBatch.status}`],
        published_languages: [],
        failed_languages: approvedLanguages,
        urls: {} as Record<Language, string>,
      }
    }

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || process.env.NEXT_PUBLIC_SITE_URL || 'https://siaintel.com'
    const urls = approvedLanguages.reduce((acc, language) => {
      acc[language] = `${baseUrl}/${language}/news/${activeBatch.id}`
      return acc
    }, {} as Record<Language, string>)

    activeBatch.status = approvedLanguages.length === Object.keys(activeBatch.editions).length
      ? 'FULLY_PUBLISHED'
      : 'PARTIAL_PUBLISHED'

    activeBatch.published_urls = urls
    activeBatch.updated_at = Date.now()

    blackboard.write(`batch.${activeBatch.id}`, activeBatch, 'system')

    return {
      success: approvedLanguages.length > 0,
      blocked: false,
      blocking_reasons: [],
      published_languages: approvedLanguages,
      failed_languages: (Object.keys(activeBatch.editions) as Language[]).filter(
        (language) => !approvedLanguages.includes(language)
      ),
      urls,
    }
  }
}

export type {
  BatchJob,
  ChiefEditorDecision,
  EditionPlan,
  Language,
  LanguageEdition,
  MasterIntelligenceCore,
} from './core-types'
